# Generated by Django 3.0.7 on 2025-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
    ]
